# Default values for docbroker.chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

###User Name/ID
serviceName: helloworld-dbr

### Docker Images ###  
images:
  repository : 192.168.0.48:5000
  contentserver :
    name : contentserver/centos/stateless/cs
    tag : 16.7.1000.0847
  pullPolicy : IfNotPresent
  pullSecrets:

### Upgrade parameters like 16.4 to 16.7
upgrade:
  majorUpgrade: false
  currentVersion: 16.4
  
### CS Secret ###
secret:
  name: cs-secret-config
  
### Dockbroker ###
docbroker:
  replicaCount: 2
  installerUI : silent

#External Docbroker
# Use the command "kubectl exec -ti tcp-port-availability-donotdelete-0 /bin/bash /execute.sh" to find available ports to be configured for nativeExtPort and sslExtPort
ExtDocbroker:
  enable: false  
  extNativeNodePort: 
  extSSLNodePort: 
  
### Greylog ###
graylog:
  enable: false
  image: 10.9.57.7/graylog-sidecar@sha256:8719e2f5601dca31123f7618cc1f7fc569503e32e0d78340fc293288bb04c422
  server: 10.9.57.15
  port: 9000

### Ports ###
ports:
  docbrokerPort: 1489
  docbrokrSSLport: 1490
  extNativePort: 1491
  extSSLPort: 1492

### Persistent Volume ###
persistentVolume:
  vctName: dbr-vct
  accessModes: ReadWriteOnce
  size: 1Gi
  storageClass: standard
  logVctAccessModes: ReadWriteOnce
  logVctSize: 2Gi
  logVctStorageClass: standard
   
 ### resources ###
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 200Mi

nodeSelector: {}

tolerations: []

affinity: {}
