{{ if eq .Values.ExtDocbroker.enable true }}
#Nodeport Service exposing docbroker native port
apiVersion: v1
kind: Service
metadata:
  name: native-{{ .Values.serviceName }}
  labels:
    app: native-{{ .Values.serviceName }}    
spec:
  type: NodePort
  ports:
  - port: {{ .Values.ports.extNativePort }} 
    nodePort: {{ .Values.ExtDocbroker.extNativeNodePort }}
    protocol: TCP
    name: xdbrnativeport
    targetPort: {{ .Values.ports.extNativePort }}  
  selector:
    app: {{ .Values.serviceName }}
---
#Nodeport Service exposing docbroker ssl port
apiVersion: v1
kind: Service
metadata:
  name: ssl-{{ .Values.serviceName }}
  labels:
    app: ssl-{{ .Values.serviceName }}    
spec:
  type: NodePort
  ports:
  - port: {{ .Values.ports.extSSLPort }}
    nodePort: {{ .Values.ExtDocbroker.extSSLNodePort }}
    protocol: TCP
    name: xdbrsslport
    targetPort: {{ .Values.ports.extSSLPort }}
  selector:
    app: {{ .Values.serviceName }}
{{ end }}