# This secret is used for CS, DB

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  rootPassword: {{ default "" .Values.contentserver.install.root.password | b64enc | quote }}
  installOwner: {{ default "" .Values.contentserver.installOwner.userName | b64enc | quote }}
  installOwnerPassword: {{ default "" .Values.contentserver.installOwner.password | b64enc | quote }}
  globalRegistryPassword: {{ default "" .Values.contentserver.globalRegistry.password | b64enc | quote }}
  aekAlgorithm: {{ default "" .Values.contentserver.aek.algorithm | b64enc | quote }}
  aekPassphrase: {{ default "" .Values.contentserver.aek.passphrase | b64enc | quote }}
  appServerAdminPassword: {{ default "" .Values.contentserver.install.appserver.admin.password | b64enc | quote }}
  tsAppServerAdminpassword: {{ default "" .Values.thumbnailServer.appServerPassword | b64enc | quote }}
  dbUserName: {{ default "" .Values.database.userName | b64enc | quote }}
  dbPassword: {{ default "" .Values.database.password | b64enc | quote }}
  dbCertificate: {{ default "" .Values.database.certificate | b64enc }}
  docbasePassword: {{ default "" .Values.docbase.password | b64enc | quote }} 
  docbaseLicensesRecordManager: {{ default "" .Values.docbase.licenses.recordManager | b64enc | quote }} 
  docbaseLicensesPRM:  {{ default "" .Values.docbase.licenses.prm | b64enc | quote }} 
  docbaseLicensesFedRecdService: {{ default "" .Values.docbase.licenses.fedRecdService | b64enc | quote }}
  docbaseLicensesRPS: {{ default "" .Values.docbase.licenses.rps | b64enc | quote }}
  docbaseLicensesSnaplockstore: {{ default "" .Values.docbase.licenses.snaplockstore | b64enc | quote }}
  docbaseLicensesXMLstore: {{ default "" .Values.docbase.licenses.xmlstore | b64enc | quote }}
  docbaseLicensesStorageaware: {{ default "" .Values.docbase.licenses.storageaware | b64enc | quote }}
  docbaseLicensesTrusted: {{ default "" .Values.docbase.licenses.trusted | b64enc | quote }}
  docbaseLicensesHighVolumeServer: {{ default "" .Values.docbase.licenses.highVolumeServer | b64enc | quote }}
  s3StoreBaseUrl: {{ default "" .Values.s3Store.s3StoreBaseUrl | b64enc | quote }}
  s3StoreCredentialID: {{ default "" .Values.s3Store.s3StoreCredentialID | b64enc | quote }}
  s3StoreCredentialKEY: {{ default "" .Values.s3Store.s3StoreCredentialKEY | b64enc | quote }}