# Default values for databse.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

###User Name/ID
serviceName: dctmdb-pg

### Docker Images ###  
images:
  repository : localhost:5000
  db :
    name : cs/pg
    tag : 10.3
  pullPolicy : IfNotPresent
  pullSecrets:

### Database ###
database:
  replicaCount: 1
  port: 5432
  dbServicePort: 5432
  
### Persistent Volume ###
persistentVolume:
  accessModes: ReadWriteOnce
  size: 2Gi
  storageClass: standard

### ConfigMap metadata ###
configMap:
  configName: dctm-alter
  volumeName: dctm-alter-volume
  
alterParam:
  max_connections:
  default_statistics_target:
  maintenance_work_mem:
  effective_cache_size:
  wal_buffers:
  work_mem:
  
### resources ###
resources:
  limits:
    cpu: 4000m
    memory: 8Gi
  requests:
    cpu: 100m
    memory: 400Mi

nodeSelector: {}

tolerations: []

affinity: {}
