#CS StatefulSet

apiVersion: apps/v1
kind: StatefulSet
metadata:
   name: {{ .Values.userName }}
spec:
  serviceName: {{ .Values.userName }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.userName }}
  template:
    metadata:
      labels:
        app: {{ .Values.userName }}
    spec:
      containers:      
      - name: {{ .Values.userName }}
        image: {{ .Values.images.repository }}/{{ .Values.images.customscriptimage.name }}:{{ .Values.images.customscriptimage.tag }}
        readinessProbe:
          exec: {
            command: [
              bash,
              -c,
              /cscustomscript-readiness.sh
            ]            
          }
          initialDelaySeconds: 60
          periodSeconds: 120
          failureThreshold: 2
          successThreshold: 1
          timeoutSeconds: 60
        env:
        - name: KUBERNETES
          value: "true"        
        volumeMounts:        
        - mountPath: /customscripts
          name: custom-script-pvc
          subPath: {{ .Values.custom.PVCSubPath }}        
      volumes:
        - name: custom-script-pvc
          persistentVolumeClaim:
            claimName: {{ .Values.custom.scriptPVCname }}
      restartPolicy: Always